---
repos:
  ###
  ### All files
  ###
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace

  ###
  ### Rust
  ###
  - repo: local
    hooks:
      - id: rust-check
        name: runs rustfmt, clippy and cargo
        language: system
        entry: make -C rust check
        pass_filenames: false
        always_run: true
      - id: rust-test
        name: runs rust unit tests
        language: system
        entry: make -C rust test
        pass_filenames: false
        always_run: true
